-- CREATE DATABASE tododb;

USE tododb;

-- CREATE TABLE Task (
-- 	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
--     title VARCHAR(50) NULL,
--     content VARCHAR(500) NULL,
--     is_deleted BOOLEAN NOT NULL DEFAULT FALSE
-- );

-- DROP TABLE Task;

CREATE TABLE USER(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(64) NOT NULL UNIQUE,
    email VARCHAR(120) NOT NULL UNIQUE,
    password_hash VARCHAR(128) NOT NULL,
    full_name VARCHAR(200) NULL
);

-- DROP TABLE USER